import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

import { Navigation } from "@/components/ui/navigation";
import Footer from "@/components/ui/footer";
import Link from "next/link";
import Logo from "@/components/Logo";
import { footer_menu } from "@/lib/nav-links";

import SocialBar from "@/components/social-bar";
import ModeToggle from "@/components/mode-toggle";

const siteUrl = "https://www.lopezed.com";

const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Eddie Lopez",
  alternateName: "Eduardo Lopez",
  url: siteUrl,
  jobTitle: "Design Engineer",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Fresno",
    addressRegion: "CA",
    addressCountry: "US",
  },
  knowsAbout: [
    "Design Engineering",
    "Frontend Development",
    "UI/UX Design",
    "React",
    "Next.js",
    "TypeScript",
    "Design Systems",
    "Web Accessibility",
  ],
  sameAs: [
    "https://www.linkedin.com/in/eddie98lopez/",
    "https://github.com/Eddie98Lopez",
    "https://www.centeredmarketing.com/team/b7002c46-8126-4d65-8096-8cd89ab7cece",
  ],
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation />
          {children}
          <Footer>
            <div className="max-w-[1600px] w-full h-full flex flex-col m-auto content-center items-center lg:grid lg:grid-cols-2 gap-16">
              <div className="order-1 flex gap-12 items-center ">
                <Logo className="w-30 h-auto fill-(--text-base)" />
                <div>
                  <p>
                    <Link href="mailto:info@lopezed.com" className="font-bold">
                      info@lopezed.com
                    </Link>
                  </p>
                  <p>Based in Fresno, CA</p>
                </div>
              </div>
              <div className="order-3">
                <SocialBar />
              </div>
              <div className="order-2 row-span-2">
                <ul className="flex flex-col gap-2 content-center items-center lg:items-end">
                  {footer_menu.map((item, i) => {
                    return (
                      <Link
                        key={`footer-link-${i}`}
                        href={item.href}
                        className="uppercase lg:text-right font-bold hover:bg-secondary hover:text-primary p-2"
                      >
                        {item.label}
                      </Link>
                    );
                  })}
                </ul>
              </div>
              <div className="order-4 col-span-full text-center">
                <ModeToggle /> <div>© copyright Lopezed LLC 2026</div>
              </div>
            </div>
          </Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
